# Introdução 

Este Trabalho de Conclusão de Curso apresenta uma pesquisa sobre Van Gogh, onde será abordado abordada a vida do artista, sua trajetória, estado psicológico e como o último influenciava suas obras. Para perceber como seus aspectos psicológicos afetavam suas obras, escolhemos analisar a pintura "A Noite Estrelada", onde enxergamos parte da trajetória do artista.
Van Gogh é um artista muito conhecido atualmente, embora tenha vivido no decorrer do século XIX. Uma das principais perguntas deste trabalho de conclusão é: como o pintor era visto naquela época? Como e quais os possíveis significados de suas diversas obras?
Como é citado anteriormente, o assunto principal é o estado psicológico do artista. É vista relevância nesta problemática, pois na época que o pintor vivia não era fácil ser artista, e com este contexto, junto de suas dificuldades pessoais em geral, acreditamos que seu quadro psicológico tenha se agravado.
Tentaremos entender por que o artista ficou reconhecido apenas após sua morte e porque tem sido tão retomado no contexto cultural atual
Este trabalho tem como objetivo mudar a perspectiva das pessoas sobre as obras do pintor, apresentando alguns artigos de psicologia e arte, assim trazendo uma maior compreensão sobre o assunto para todos.
Será abordado também o porquê de o pintor apenas ficar conhecido após sua morte.

“Grandes coisas não são feitas por impulso, mas por uma série de pequenas coisas reunidas.”
- Vicent Van Gogh
